const list = [
  {
    id: 1,
    title: "The Last of the Mohicans",
    author: "James Fenimore Cooper",
    price: 50,
    image: "https://m.media-amazon.com/images/I/71tYAyL590L._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    price: 56,
    image: "https://m.media-amazon.com/images/I/81yNWdTnoUL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Lord of the Flies",
    author: "William Golding and E. L. Epstein",
    price: 67,
    image: " https://m.media-amazon.com/images/I/81WUAoL-wFL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Frankenstein",
    author: "Leo Tolstoy, Louise Maude - translator, et al.",
    price: 67,
    image: "https://m.media-amazon.com/images/I/81zFedw-09L._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "Little Women (AmazonClassics Edition)",
    author: "Louisa May Alcott",
    price: 65,
    image: "https://m.media-amazon.com/images/I/71i9TStgFaL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "The Scarlet Letter (Signet Classics)",
    author: "Nathaniel Hawthorne , Brenda Wineapple, et al",
    price: 78,
    image: "https://m.media-amazon.com/images/I/81-lITaHeQL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "The Federalist Papers",
    author: "Alexander Hamilton , James Madison , et al.",
    price: 35,
    image: "https://m.media-amazon.com/images/I/81wRDKH5q6L._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    price: 23,
    image: "https://m.media-amazon.com/images/I/81i5nX1520L._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Beyond Good and Evil",
    author: "Friedrich Nietzsche and Helen Zimmern",
    price: 34,
    image: "https://m.media-amazon.com/images/I/81+QRxiOSqL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "The Art of War",
    author: "Fyodor Dostoyevsky, James Anderson Foster, et al.",
    price: 23,
    image: "https://m.media-amazon.com/images/I/71iQLkDkuqL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Moby Dick",
    author: "Herman Melville",
    price: 26,
    image: "https://m.media-amazon.com/images/I/813G3AAmNJL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Dracula",
    author: "Bram Stoker",
    price: 14,
    image: "https://m.media-amazon.com/images/I/91mnJ6ePWpL._AC_UL320_.jpg",
    amount: 1,
  },
];
export default list;
